# zabbix/agent

# Install
- name: Check Zabbix Repository
  become: yes
  stat: path=”/etc/yum.repos.d/zabbix.repo”
  register: is_zabbix_repo

- name: Install Zabbix Repository
  become: yes
  yum:
    state: present
    name: http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-agent-3.0.31-1.el6.x86_64.rpm
  when: not is_zabbix_repo.stat.exists

- name: Check zabbix_agentd
  become: yes
  stat: path=”/usr/sbin/zabbix_agentd”
  register: is_zabbix_agentd

#- block:
#- name: enable Zabbix Repository
#  become: yes
#  replace:
#    dest: “/etc/yum.repos.d/zabbix.repo”
#    regexp: “enabled=.*”
#    replace: “enabled=1”

- name: Install zabbix-agent
  become: yes
  yum:
    state: present
  name: “zabbix-agent-{{ zabbix_version }}-1.el7.x86_64”

#- name: Disable Zabbix Repository
#  become: yes
#  replace:
#    dest: “/etc/yum.repos.d/zabbix.repo”
#    regexp: “enabled=.*”
#    replace: “enabled=0”
#  when: not is_zabbix_agentd.stat.exists

# Copy Configure	 
- name: Copy zabbix-agent Config
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/zabbix/{{ item }}"
  with_items:
    - zabbix_agentd.conf
  notify: Restart zabbix-agent

- name: Copy Logrotate Config
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logrotate.d/{{ item }}"
  with_items:
    - zabbix-agent

